### PR TITLE
docs: update

### PR DESCRIPTION
**Pull request by gucovip**

### CODE REVIEW

**Comment by adamlui** [comment]
Sup @gucovip, for DuckDuckGPT & BraveGPT, they are actually chatbots now (the screenshot/demo are outdated):

<div align="center">

image
image

</div>

But they are also userscripts, so that begs the question which is better category.

But also, in the future, they will be added to Chrome/Edge store as extensions, so they will also be browser extensions!

So if a tool belongs to multiple categories, should they be listed in all of them? Or if only one, what should be the rule to pick which one category? (We should consider the reader and how it best serves them)

**Comment by edison1105** [comment]
> So if a tool belongs to multiple categories, should they be listed in all of them?

yes.

**Comment by adamlui** [comment]
@edison1105 ok, and can you install duckduckgpt, then visit duckduckgpt.com to confirm it is indeed also a chatbot that uses OpenAI to reply to you and remembers your previous messages?

**Comment by edison1105** [comment]
@adamlui added them to chatbot category via e304fd9cf3a641a48ae338667490acbf569e1c7c

**Pull request merged**
